linkPrefix = "/doxity-simpleton"
name = "doxity-simpleton"
version = "1.0.0"
description = "Solidity Documentation"
buildTime = 2018-04-05T19:46:33.291Z
target = "doxity"
src = "contracts/*"
dir = "pages/docs"
out = "docs"
author = "Ryan Hendricks"
homepage = "https://ryanhendricks.github.io/doxity-simpleton/"

[interaction]